version: '3.8'
name: support
services:
  # Portainer CE
  # Managing containers via nice web UI
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: unless-stopped
    ports:
      - 8000:8000 # Agent
      - 9000:9000 # Web UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER}/portainer/data:/data

  # Watchtower
  # A solution for automating Docker container base image updates
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    environment:
      WATCHTOWER_CLEANUP: 'true'
      WATCHTOWER_WARN_ON_HEAD_FAILURE: 'never'
      WATCHTOWER_NO_STARTUP_MESSAGE: 'true'
      WATCHTOWER_SCHEDULE: '0 0 5 * * 6'
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: ${EMAIL_SERVER_ADDRESS}
      WATCHTOWER_NOTIFICATION_EMAIL_TO: ${EMAIL_SERVER_ADDRESS}
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: ${EMAIL_SERVER}
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: ${EMAIL_SERVER_PORT}
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: ${EMAIL_SERVER_USER}
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: ${EMAIL_SERVER_PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  # Samba
  # Remote access to the file system
  samba:
    container_name: samba
    image: dperson/samba
    restart: unless-stopped
    env_file: .env
    environment:
      USERID: ${PUID}
      GROUPID: ${PGID}
    volumes:
      - ..:/mnt/smart-home
      - ${STORAGE}/media:/mnt/media
    ports:
      - 139:139
      - 445:445
      - 137:137/udp
      - 138:138/udp
    command: >
      samba.sh
        -s "media;/mnt/media;yes;no;no;all"
        -s "smart-home;/mnt/smart-home;yes;no;no;all"
        -u "${SAMBA_USER};${SAMBA_PASSWORD}"

  # Glance
  # A self-hosted dashboard that puts all feeds in one place
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./glance:/app/config
      - /mnt:/mnt:ro
    ports:
      - 8888:8080
