version: '3.8'
name: home
services:
  # Bitwarden
  # Vaultwarden is a Rust implementation of Bitwarden API for less powerful devices
  bitwarden:
    container_name: bitwarden
    image: vaultwarden/server
    restart: unless-stopped
    env_file: .env
    environment:
      WEBSOCKET_ENABLED: 'true'
    ports:
      - 3838:80
      - 3812:3012
    volumes:
      - ${DOCKER}/bitwarden:/data

  # Wallos
  # Subscriptions management application
  wallos:
    container_name: wallos
    image: bellamy/wallos
    restart: unless-stopped
    ports:
      - 8282:80/tcp
    env_file: .env
    volumes:
      - ${DOCKER}/wallos/db:/var/www/html/db
      - ${DOCKER}/wallos/logos:/var/www/html/images/uploads/logos
