#
# Sensor
#
# https://www.home-assistant.io/integrations/sensor/
#

sensor:
  # MQTT Bridge
  - platform: mqtt
    name: Bridge state
    state_topic: "zigbee2mqtt/bridge/state"
    icon: mdi:router-wireless
  
  # System Monitor
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: swap_use_percent
      - type: processor_use
      - type: memory_use_percent

  # Humidifier
  - platform: template
    sensors:
      humidifier_humidity:
        value_template: >-
          {{ state_attr('fan.humidifier', 'humidity') }}
      humidifier_temperature:
        value_template: >-
          {{ state_attr('fan.humidifier', 'temperature') | round(2) }}

  # Purifier
  - platform: template
    sensors:
      purifier_humidity:
        value_template: >-
          {{ state_attr('fan.purifier', 'humidity') }}
      purifier_temperature:
        value_template: >-
          {{ state_attr('fan.purifier', 'temperature') | round(2) }}
      purifier_aqi:
        value_template: >-
          {{ state_attr('fan.purifier', 'aqi') }}

  # Temperature
  - platform: min_max
    name: Home Temperature
    type: mean
    entity_ids:
      - sensor.living_room_conditions_sensor_temperature
      - sensor.humidifier_temperature
      - sensor.purifier_temperature
  - platform: min_max
    name: Living Room Temperature
    type: mean
    entity_ids:
      - sensor.living_room_conditions_sensor_temperature
      - sensor.purifier_temperature
  - platform: min_max
    name: Bedroom Temperature
    type: mean
    entity_ids:
      - sensor.living_room_conditions_sensor_temperature
      - sensor.humidifier_temperature

  # Humidity
  - platform: min_max
    name: Home Humidity
    type: mean
    entity_ids:
      - sensor.living_room_conditions_sensor_humidity
      - sensor.humidifier_humidity
      - sensor.purifier_humidity
  - platform: min_max
    name: Living Room Humidity
    type: mean
    entity_ids:
      - sensor.living_room_conditions_sensor_humidity
      - sensor.purifier_humidity
  - platform: min_max
    name: Bedroom Humidity
    type: mean
    entity_ids:
      - sensor.living_room_conditions_sensor_humidity
      - sensor.humidifier_humidity

  # Eco City AQI
  - platform: rest
    name: nyvky_aqi
    resource: https://eco-city.org.ua/output.json
    value_template: >-
      {% set station = 'EcoCity_867' %}
      {# #}
      {% macro aqi(aqihigh, aqilow, conchigh, conclow, conc) -%}
        {{ ((aqihigh - aqilow) / (conchigh - conclow) * (conc - conclow) + aqilow) | int }}
      {%- endmacro %}
      {# #}
      {% for sensor in value_json %}
        {% if sensor.id == station %}
          {% set conc = sensor.pollutants[0].value | float %}
          {% if conc >= 0 and conc <= 50 %}
              {{ aqi(50, 0, 12, 0, conc) }}
          {% elif conc > 50 and conc <= 100 %}
              {{ aqi(100, 51, 35.4, 12.1, conc) }}
          {% elif conc > 100 and conc <= 150 %}
              {{ aqi(150, 101, 55.4, 35.5, conc) }}
          {% elif conc > 150 and conc <= 200 %}
              {{ aqi(200, 151, 150.4, 55.5, conc) }}
          {% elif conc > 200 and conc <= 300 %}
              {{ aqi(300, 201, 250.4, 150.5, conc) }}
          {% elif conc > 300 and conc <= 400 %}
              {{ aqi(400, 301, 350.4, 250.5, conc) }}
          {% elif conc > 400 and conc <= 500 %}
              {{ aqi(500, 401, 500.4, 350.5, conc) }}
          {% else %}
              unknown
          {% endif %}
        {% endif %}
      {% endfor %}
    scan_interval: 120 # every 2 minutes
    json_attributes_path: "$.[?(@.id=='EcoCity_867')]"
    json_attributes:
      - id
      - cityName
      - stationName
      - localName
      - latitude
      - longitude
      - timezone
      - pollutants

  # Kyiv Smart Card
  #
  # FIXME: Token gets invalid every 24 hours. Needs renewal.
  #
  # - platform: rest
  #   name: kyivsmartcard_denys
  #   resource: https://my.kyivcity.gov.ua/api/me/travel-cards
  #   headers:
  #     User-Agent: Home Assistant
  #     Content-Type: application/json
  #     Connection: keep-alive
  #     Authorization: !secret kyivsmartcard_denys_token
  #   value_template: >-
  #     {{ value_json[0].assets.purchases[0].residualUnits }}
  #   json_attributes_path: "$.[0]"
  #   json_attributes:
  #     - code
  #     - name
  #     - createdAt
