version: '3.8'
services:
  kitchenowl-web:
    container_name: kitchenowl-web
    image: tombursch/kitchenowl-web:dev
    restart: unless-stopped
    environment:
      BACK_URL: kitchenowl:5000
    ports:
      - 3434:80
    depends_on:
      - kitchenowl

  kitchenowl:
    container_name: kitchenowl
    image: tombursch/kitchenowl:dev
    restart: unless-stopped
    # ports: # Should only be needed if you're not using docker-compose
    #   - "5000:5000" # uwsgi protocol
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      # - FRONT_URL=http://localhost # Optional should not be changed unless you know what youre doing
    volumes:
      - ${DOCKER}/kitchenowl:/data
