version: '3.8'
name: network
services:
  # Nginx Proxy Manager
  # A proxy managerment for services. Basically a Web UI for Nginx.
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:2.12.3
    restart: unless-stopped
    ports:
      - 80:80 # Public HTTP Port
      - 443:443 # Public HTTPS Port
      - 8081:81 # Admin Web Port
    volumes:
      - ${DOCKER}/nginx-proxy-manager/data:/data
      - ${DOCKER}/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    labels:
      com.centurylinklabs.watchtower.monitor-only: true

  # Pi-hole
  # A DNS ad blocker
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - '53:53/tcp' # DNS
      - '53:53/udp' # DNS
      - '67:67/udp' # DHCP
      - '5300:80/tcp' # WEB UI
    environment:
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
    volumes:
      - ${DOCKER}/pihole/etc-pihole:/etc/pihole
      - ${DOCKER}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    labels:
      com.centurylinklabs.watchtower.monitor-only: true

  # Wireguard
  # Performant VPN for accessing home network + web ui
  wireguard:
    container_name: wireguard
    image: ghcr.io/wg-easy/wg-easy
    restart: unless-stopped
    environment:
      WG_HOST: ${WIREGUARD_HOST}
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    volumes:
      - ${DOCKER}/wireguard:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      com.centurylinklabs.watchtower.monitor-only: true
