version: '3.8'
name: wapydev
services:
  db:
    container_name: wapydev-db
    image: postgres:17.4
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-wapydev}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB:-wapydev}
    ports:
      - 5432:5432
    volumes:
      - ${DOCKER}/wapydev/db:/var/lib/postgresql/data

  app:
    container_name: wapydev-app
    image: ghcr.io/meceware/wapy.dev:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3131:3000
    depends_on:
      - db

  cron:
    container_name: wapydev-cron
    image: alpine:3.21
    restart: unless-stopped
    command: >
      sh -c 'while true; do
        /usr/bin/flock -n /tmp/wapy.lockfile wget -qO- app:3000/api/cron/;
        sleep 60;
      done'
    depends_on:
      - app
