title: Smart Home
subtitle: Сервіси нашого розумного дому
icon: fas fa-house-chimney-user
header: true
footer: false
# connectivityCheck: true
theme: default

# Header links
links:
  - name: Smart Home Docs
    icon: fas fa-book
    url: 'https://denysdovhan.com/smart-home'

# Services
services:
  - name: Smart Home
    icon: fas fa-cloud
    items:
      - name: Home Assistant
        subtitle: Інтерфейс для розумного дому
        logo: https://upload.wikimedia.org/wikipedia/commons/6/6e/Home_Assistant_Logo.svg
        url: https://home.dovhan-nyvky.pp.ua
        target: _blank
      - name: Vaultwarden
        subtitle: Менеджер паролів (Bitwarden)
        logo: https://raw.githubusercontent.com/dani-garcia/vaultwarden/master/resources/vaultwarden-icon.svg
        url: https://bitwarden.dovhan-nyvky.pp.ua
        target: _blank
  - name: Media
    icon: fas fa-tv
    items:
      - name: Plex
        subtitle: Медіа сервер
        logo: https://www.vectorlogo.zone/logos/plextv/plextv-tile.svg
        url: https://app.plex.tv
        target: _blank
        tag: external
      - name: Transmission
        subtitle: Торрент-клієнт
        logo: https://transmissionbt.com/assets/images/Transmission_icon.png
        url: https://torrents.dovhan-nyvky.pp.ua
        target: _blank
      - name: Sonarr
        type: Sonarr
        subtitle: Моніторинг серіалів
        logo: https://avatars.githubusercontent.com/u/1082903
        url: https://sonarr.dovhan-nyvky.pp.ua
        target: _blank
        apikey: f3acba3aa681403198a44b38fa4090dc
      - name: Radarr
        type: Radarr
        subtitle: Моніторинг фільмів
        logo: https://avatars.githubusercontent.com/u/25025331
        url: https://radarr.dovhan-nyvky.pp.ua
        target: _blank
        apikey: 06fb87389b8d432190ed8f5f89cd757f
      - name: Prowlarr
        type: Prowlarr
        subtitle: Проксі-АРІ для торрентів
        logo: https://avatars.githubusercontent.com/u/73049443
        url: https://prowlarr.dovhan-nyvky.pp.ua
        target: _blank
        apikey: e902364b4fa44c6db1df1bd3b471298e
  - name: Система
    icon: fas fa-server
    items:
      - name: Portainer
        subtitle: Керування сервісами
        logo: https://cdn.worldvectorlogo.com/logos/portainer.svg
        url: https://portainer.dovhan-nyvky.pp.ua
        target: '_blank'
      - name: Nginx Proxy Manager
        subtitle: Керування доступом до внутрішніх сервісів
        logo: https://nginxproxymanager.com/icon.png
        url: https://nginx.dovhan-nyvky.pp.ua
        target: '_blank'
      - name: Pi-hole
        logo: https://upload.wikimedia.org/wikipedia/commons/0/00/Pi-hole_Logo.png
        subtitle: Блокувальник реклами
        url: https://pihole.dovhan-nyvky.pp.ua/admin
      - name: Proxmox
        subtitle: Менеджер для серверів
        logo: https://camo.githubusercontent.com/cb6c50486cf76c4a9a9a4c7811f8bf97f59f7512d11119a386021086997cae0e/68747470733a2f2f7777772e70726f786d6f782e636f6d2f696d616765732f70726f786d6f782f50726f786d6f785f73796d626f6c5f7374616e646172645f6865782e706e67
        url: https://proxmox.dovhan-nyvky.pp.ua
        target: _blank
      - name: Cloudflare
        subtitle: Керування зовнішнім доступом
        logo: https://cdn.svgporn.com/logos/cloudflare.svg
        url: https://dash.cloudflare.com/e4a4bd33bf65e2458b01ea8b4fcdfbe9/dovhan-nyvky.pp.ua
        target: _blank
        tag: external
