- id: automatic_theme_change
  alias: Automatic Theme Change
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sun.sun
  action:
    - service_template: frontend.set_theme
      data_template:
        name: >
          {% if states.sun.sun.state == "above_horizon" %}
            default
          {% else %}
            midnight
          {% endif %}

- alias: Home Assistant Release notification
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    service: notify.denys
    data_template:
      title: '游꿀 New Home Assistant Release'
      message: "Home Assistant  {{ state_attr('binary_sensor.updater', 'newest_version') }}  is now available."

- id: torrent_completed_notification
  alias: Notify about completed torrent
  trigger:
    platform: event
    event_type: transmission_downloaded_torrent
  action:
    - service: notify.all
      data_template:
        title: "拘勇 Transmission"
        message: "{{trigger.event.data.name}} 향햟쒫썛쫨햟햤햣햫!"
    - service: tts.google_say
      data_template:
        entity_id: media_player.google_home_mini
        language: uk
        message: >
          {{
            [
              "햑쮐햣햫혝 향햟쒫썛쫨햟햤햣햫!",
              "뉋썜 혟햟햧햩 향햟쒫썛쫨햟햤햣햫!",
              "햓햟햧햩 햡쮐쮏쒫쟳 햢 햣햣햡햩혪햢혞!",
              "행햟쒫썛쫨햟햤햣햫햫혪 향햟쒫왐혣햣햫!"
            ] | random
          }} 
