version: '3.8'
name: apps
services:
  # Bitwarden
  # Vaultwarden is a Rust implementation of Bitwarden API for less powerful devices
  bitwarden:
    container_name: bitwarden
    image: vaultwarden/server
    restart: unless-stopped
    ports:
      - 3838:80
      - 3812:3012
    volumes:
      - ${DOCKER}/bitwarden:/data

  # Mealie
  # Mealie is a self-hosted recipe manager and meal planner
  mealie:
    container_name: mealie
    image: ghcr.io/mealie-recipes/mealie:latest
    restart: unless-stopped
    ports:
      - 9925:9000
    volumes:
      - ${DOCKER}/mealie:/app/data
    env_file: .env
    environment:
      ALLOW_SIGNUP: false
      ALLOW_PASSWORD_LOGIN: false
      BASE_URL: https://mealie.${PUBLIC_DOMAIN}
      # Emails
      SMTP_HOST: ${SMTP_HOST}
      SMTP_USER: ${SMTP_LOGIN}
      SMTP_PASSWORD: ${SMTP_TOKEN}
      SMTP_FROM_EMAIL: mealie@${PUBLIC_DOMAIN}
      # Open AI
      OPENAI_API_KEY: ${MEALIE_OPENAI_API_KEY}
      # OIDC
      OIDC_AUTH_ENABLED: true
      OIDC_SIGNUP_ENABLED: true
      OIDC_REMEMBER_ME: true
      OIDC_PROVIDER_NAME: Pocket ID
      OIDC_CONFIGURATION_URL: ${MEALIE_OIDC_CONFIGURATION_URL}
      OIDC_CLIENT_ID: ${MEALIE_OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${MEALIE_OIDC_CLIENT_SECRET}
    deploy:
      resources:
        limits:
          memory: 1000M

  # Wallos
  # Wallos is a self-hosted wallboard application for displaying information on screens
  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    ports:
      - 8282:80/tcp
    environment:
      TZ: ${TZ}
    volumes:
      - ${DOCKER}/wallos/db:/var/www/html/db
      - ${DOCKER}/wallos/logos:/var/www/html/images/uploads/logos
    restart: unless-stopped
