version: '3.8'
name: apps
services:
  # Bitwarden
  # Vaultwarden is a Rust implementation of Bitwarden API for less powerful devices
  bitwarden:
    container_name: bitwarden
    image: vaultwarden/server
    restart: unless-stopped
    env_file: .env
    environment:
      WEBSOCKET_ENABLED: 'true'
    ports:
      - 3838:80
      - 3812:3012
    volumes:
      - ${DOCKER}/bitwarden:/data

  # Mealie
  # Mealie is a self-hosted recipe manager and meal planner
  mealie:
    container_name: mealie
    image: ghcr.io/mealie-recipes/mealie:latest
    restart: unless-stopped
    ports:
      - 9925:9000
    volumes:
      - ${DOCKER}/mealie:/app/data
    deploy:
      resources:
        limits:
          memory: 1000M
    env_file: .env
    environment:
      ALLOW_SIGNUP: false
      BASE_URL: https://mealie.${PUBLIC_DOMAIN}
      OPENAI_API_KEY: ${MEALIE_OPENAI_API_KEY}
      OPENAI_MODEL: gpt-4o-mini
